import {Images} from '../../theme';

export const data = [
  {
    id: 1,
    image: Images.Welcome,
    name: 'Rahul',
    age: '22',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 2,
    image: Images.bgImage,
    name: 'Sunil',
    age: '32',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 3,
    image: Images.bgImage2,
    name: 'Sanjay',
    age: '28',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 4,
    image: Images.bgImage,
    name: 'Sandeep',
    age: '25',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 5,
    image: Images.Welcome,
    name: 'Hardik',
    age: '24',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 6,
    image: Images.bgImage2,
    name: 'Ramesh',
    age: '28',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 7,
    image: Images.Welcome,
    name: 'Pradeep',
    age: '26',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
];
