export const COUNTRY_LIST = 'COUNTRY_LIST';
export const FAMILY_VALUE = 'FAMILY_VALUE';
export const LANGUAGE_LIST = 'LANGUAGE_LIST';
export const MARITIAL_STATUS = 'MARITIAL_STATUS';
export const ONBEHALF_LIST = 'ONBEHALF_LIST';
export const RELIGION_LIST = 'RELIGION_LIST';
export const STATE_LIST = 'STATE_LIST';
export const COLOUR_LIST = 'COLOUR_LIST';
export const JOBTYPE_LIST = 'JOBTYPE_LIST';
export const DISTRICT_LIST = 'DISTRICT_LIST';
export const HEIGHT_LIST = 'HEIGHT_LIST';
export const SALARY_LIST = 'SALARY_LIST';
export const HOBBIES_LIST = 'HOBBIES_LIST';
export const USER_DASHBOARD = 'USER_DASHBOARD';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_REQUEST_SENT = 'USER_REQUEST_SENT';
export const USER_RECEVIED_REQUEST = 'USER_RECEVIED_REQUEST';
export const USER_REQUEST_ACCEPTED = 'USER_REQUEST_ACCEPTED';
export const USER_CANCEL_REQUEST = 'USER_CANCEL_REQUEST';
export const USER_BLOCK = 'USER_BLOCK';
export const USER_BLOCKED_LIST = 'USER_BLOCKED_LIST';
export const USER_UNBLOCK = 'USER_UNBLOCK';

//basic info update
export const FIRST_NAME = 'FIRST_NAME';
export const LAST_NAME = 'LAST_NAME';
export const GENDER_SELECT = 'GENDER_SELECT';
export const DATE_OF_BIRTH = 'DATE_OF_BIRTH';
export const CHILDREN_SELECT = 'CHILDREN_SELECT';
export const SALARY_UPDATE = 'SALARY_UPDATE';
export const MARITIAL_UPDATE = 'MARITIAL_UPDATE';
export const ONBEHALF_UPDATE = 'ONBEHALF_UPDATE';

//update address

export const COUNTRY_ID = 'COUNTRY_ID';
export const STATE_ID = 'STATE_ID';
export const CITY_ID = 'CITY_ID';
export const CITY_NAME = 'CITY_NAME';
export const ADDRESS = 'ADDRESS';
export const POSTAL_CODE = 'POSTAL_CODE';
export const ADDRESS_TYPE = 'ADDRESS_TYPE';

//update education
export const DEGREE = 'DEGREE';
export const INSTITUTION = 'INSTITUTION';

//update career
export const JOB_TYPE = 'JOB_TYPE';
export const OCCUPIED_COMPANY = 'OCCUPIED_COMPANY';
export const WORK_FIELD = 'WORK_FIELD';
export const WORK_AREA = 'WORK_AREA';

//update physical attributes

export const HEIGHT = 'HEIGHT';
export const WEIGHT = 'WEIGHT';
export const COMPLEXION = 'COMPLEXION';
export const BLOOD_GROUP = 'BLOOD_GROUP';
export const BODY_TYPE = 'BODY_TYPE';
export const DISABILITY = 'DISABILITY';

// update language
export const KNOWN_LANGUAGES = 'KNOWN_LANGUAGES';
export const MOTHER_TONGUE = 'MOTHER_TONGUE';

//update hobbies
export const SELECTED_HOBBIES = 'SELECTED_HOBBIES';

//update spiritual
export const SELECTED_RELIGION = 'SELECTED_RELIGION';
export const SELECTED_RELIGION_CASTE = 'SELECTED_RELIGION_CASTE';
export const SELECTED_CASTE = 'SELECTED_CASTE';
export const SELECTED_SUB_CASTE = 'SELECTED_SUB_CASTE';
export const SELECTED_FAMILY_VALUE = 'SELECTED_FAMILY_VALUE';

//update lifestyle
export const SELECTED_DIET = 'SELECTED_DIET';
export const SELECTED_DRINK = 'SELECTED_DRINK';
export const SELECTED_SMOKE = 'SELECTED_SMOKE';

//update astronomic

export const SELECTED_TIME_OF_BIRTH = 'SELECTED_TIME_OF_BIRTH';
export const SELECTED_CITY_OF_BIRTH = 'SELECTED_CITY_OF_BIRTH';
export const SELECTED_MANGLIK = 'SELECTED_MANGLIK';

//update family info

export const FATHER_NAME = 'FATHER_NAME';
export const MOTHER_NAME = 'MOTHER_NAME';
export const SELECTED_M_BROTHER = 'SELECTED_M_BROTHER';
export const SELECTED_UM_BROTHER = 'SELECTED_UM_BROTHER';
export const SELECTED_M_SISTER = 'SELECTED_M_SISTER';
export const SELECTED_UM_SISTER = 'SELECTED_UM_SISTER';
export const SELECTED_SIBLING = 'SELECTED_SIBLING';

//update partner expectation

export const SELECTED_GENERAL = 'SELECTED_GENERAL';
export const SELECTED_PARTNER_HEIGHT = 'SELECTED_PARTNER_HEIGHT';
export const SELECTED_PARTNER_MARITAL = 'SELECTED_PARTNER_MARITAL';
export const SELECTED_PARTNER_CHILDREN = 'SELECTED_PARTNER_CHILDREN';
export const SELECTED_RESIDENCE_COUNTRY = 'SELECTED_RESIDENCE_COUNTRY';
export const SELECTED_RESIDENCE_STATE = 'SELECTED_RESIDENCE_STATE';
export const SELECTED_PARTNER_RELIGION = 'SELECTED_PARTNER_RELIGION';
export const SELECTED_PARTNER_RELIGION_CASTE =
  'SELECTED_PARTNER_RELIGION_CASTE';
export const SELECTED_PARTNER_CASTE = 'SELECTED_PARTNER_CASTE';
export const SELECTED_PARTNER_SUBCASTE = 'SELECTED_PARTNER_SUBCASTE';
export const SELECTED_SMOKING = 'SELECTED_SMOKING';
export const SELECTED_DRINKING = 'SELECTED_DRINKING';
export const SELECTED_PARTNER_DIET = 'SELECTED_PARTNER_DIET';
export const SELECTED_PARTNER_BODYTYPE = 'SELECTED_PARTNER_BODYTYPE';
export const SELECTED_PARTNER_MANGLIK = 'SELECTED_PARTNER_MANGLIK';
export const SELECTED_PARTNER_JOBTYPE = 'SELECTED_PARTNER_JOBTYPE';
export const SELECTED_PARTNER_LANGUAGE = 'SELECTED_PARTNER_LANGUAGE';
export const SELECTED_PARTNER_FAMILY_VALUE = 'SELECTED_PARTNER_FAMILY_VALUE';
export const SELECTED_PARTNER_COMPLEXION = 'SELECTED_PARTNER_COMPLEXION';

//update image

export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';
