import styles from './Styles/SubscriptionStyle';

const data = [
  {
    id: 1,
    member: 'GOLD',
    month: '3 MONTHS',
    price: '₹5,200',
    perMonth: '₹1,733 approx per Month',
    text1: 'Send unlimited Messages',
    text2: 'View upto 75 Contact Numbers',
    text3: 'Standout from other Profiles',
    text4: 'Let Matches contact you directly',
    style1: styles.textbold,
    style2: styles.textbold,
    style3: styles.textnormal,
    style4: styles.textnormal,
    point1: styles.pointPink,
    point2: styles.pointPink,
    point3: styles.pointGrey,
    point4: styles.pointGrey,
  },
  {
    id: 2,
    member: 'GOLD PLUS',
    month: '3 MONTHS',
    price: '₹5,900',
    perMonth: '₹1,966 approx per Month',
    text1: 'Send unlimited Messages',
    text2: 'View upto 150 Contact Numbers',
    text3: 'Standout from other Profiles',
    text4: 'Let Matches contact you directly',
    style1: styles.textbold,
    style2: styles.textbold,
    style3: styles.textbold,
    style4: styles.textnormal,
    point1: styles.pointPink,
    point2: styles.pointPink,
    point3: styles.pointPink,
    point4: styles.pointGrey,
  },
  {
    id: 3,
    member: 'DIAMOND',
    month: '6 MONTHS',
    price: '₹6,900',
    perMonth: '₹1,150 approx per Month',
    text1: 'Send unlimited Messages',
    text2: 'View upto 150 Contact Numbers',
    text3: 'Standout from other Profiles',
    text4: 'Let Matches contact you directly',
    style1: styles.textbold,
    style2: styles.textbold,
    style3: styles.textnormal,
    style4: styles.textnormal,
    point1: styles.pointPink,
    point2: styles.pointPink,
    point3: styles.pointGrey,
    point4: styles.pointGrey,
  },
  {
    id: 4,
    member: 'DIAMOND PLUS',
    month: '6 MONTHS',
    price: '₹9,900',
    perMonth: '₹1,650 approx per Month',
    offer: 'TOP SELLER',
    text1: 'Send unlimited Messages',
    text2: 'View upto 300 Contact Numbers',
    text3: 'Standout from other Profiles',
    text4: 'Let Matches contact you directly',
    style1: styles.textbold,
    style2: styles.textbold,
    style3: styles.textbold,
    style4: styles.textbold,
    point1: styles.pointPink,
    point2: styles.pointPink,
    point3: styles.pointPink,
    point4: styles.pointPink,
  },
  {
    id: 5,
    member: 'PLATINUM PLUS',
    month: '12 MONTHS',
    price: '₹14,900',
    perMonth: '₹1,242 approx per Month',
    offer: 'BEST VALUE',
    text1: 'Send unlimited Messages',
    text2: 'View upto 600 Contact Numbers',
    text3: 'Standout from other Profiles',
    text4: 'Let Matches contact you directly',
    style1: styles.textbold,
    style2: styles.textbold,
    style3: styles.textbold,
    style4: styles.textbold,
    point1: styles.pointPink,
    point2: styles.pointPink,
    point3: styles.pointPink,
    point4: styles.pointPink,
  },
];
export default data;
