import {Images} from '../../theme';

export const users = [
  {
    id: 1,
    phone: '1234567890',
    password: '12345678',
    name: 'John Doe',
    image: Images.bgImage,
    age: '32',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 2,
    phone: '0987654321',
    password: '12345678',
    name: 'Jane Smith',
    image: Images.bgImage2,
    age: '32',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 3,
    phone: '0987654321',
    password: '12345678',
    name: 'Jane Smith',
    image: Images.Welcome,
    age: '32',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
  {
    id: 4,
    phone: '0987654321',
    password: '12345678',
    name: 'Jane Smith',
    age: '32',
    height: "6'11",
    caste: 'Bhraman',
    subCaste: 'Paliwal',
    city: 'Jaipur',
    jobtype: 'Software Developer',
    salary: '30-50 lakhs',
    degree: 'BCA',
    maritalStatus: 'UnMarried',
  },
];
