import EStyleSheet from 'react-native-extended-stylesheet';
import {Colors, Fonts} from '../../../theme';

const styles = EStyleSheet.create({
  container: {
    paddingTop: '10rem',
    // paddingHorizontal: '20rem',
  },
  searchNotifyContent: {
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: '20rem',
    paddingTop: '13rem',
  },
  notificationBtn: {
    width: '40rem',
    height: '40rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '10rem',
    backgroundColor: Colors.white,
    borderWidth: '1rem',
    borderColor: Colors.lightGray,
  },
  notificationIcon: {
    width: '13.59rem',
    height: '16rem',
  },
  cardInnerIcon: {
    width: '20rem',
    height: '20rem',
    marginRight: '5rem',
  },
  searchInputStyle: {
    width: '100% - 106rem',
    marginRight: 'auto',
    marginBottom: '1rem',
  },
  penddingNotification: {
    position: 'absolute',
    top: '7rem',
    right: '10rem',
    backgroundColor: Colors.pink,
    borderWidth: '2rem',
    borderColor: Colors.white,
    height: '10rem',
    width: '10rem',
    borderRadius: '7.5rem',
    overflow: 'hidden',
  },
  indicatorStyle: {
    width: '6rem',
    height: '6rem',
    backgroundColor: Colors.pink,
    borderRadius: '6rem',
    left: '12%',
    bottom: '5rem',
  },
  tabBarStyle: {
    backgroundColor: Colors.lighterGray,
    marginHorizontal: '20rem',
    elevation: 0,
    shadowOpacity: 0,
  },
  labelStyle: {
    color: Colors.darkGray,
    textTransform: 'capitalize',
    margin: '0rem',
    textAlign: 'center',
    ...Fonts.style.buttonText,
    fontSize: Fonts.size.medium,
  },
  tabViewStyle: {
    flex: '1rem',
    width: '100%',
  },
  flatListView: {
    flex: 1,
    // justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  flatListStyle: {
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: '1rem',
  },
  cardsContainer: {
    // flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  cardContainer: {
    position: 'absolute',
  },
  // card: {
  //   backgroundColor: 'white',
  //   borderRadius: '30rem',
  //   overflow: 'hidden',
  //   paddingHorizontal: '15rem',
  //   alignItems: 'center',
  //   shadowColor: '#000',
  //   shadowOffset: {
  //     width: '0rem',
  //     height: '2rem',
  //   },
  //   shadowOpacity: '0.25rem',
  //   shadowRadius: '3.84rem',
  //   elevation: '5rem',
  //   marginBottom: '60rem',
  // },
  // cardInner: {
  //   backgroundColor: 'white',
  //   borderRadius: '30rem',
  //   overflow: 'hidden',
  //   paddingHorizontal: '15rem',
  //   alignItems: 'center',
  //   shadowColor: '#000',
  //   shadowOffset: {
  //     width: '0rem',
  //     height: '2rem',
  //   },
  //   shadowOpacity: '0.25rem',
  //   shadowRadius: '3.84rem',
  //   elevation: '5rem',
  //   marginBottom: '60rem',
  // },
  verifiedTextView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: '10rem',
    paddingVertical: '5rem',
    width: '90%',
  },
  verifiedText: {
    fontSize: Fonts.size.h4,
    color: '#F5F5F5',
    fontWeight: 'bold',
  },
  checkIcon: {
    width: '30rem',
    height: '30rem',
  },
  detailsView: {
    position: 'absolute',
    bottom: '15rem',
    left: '15rem',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    elevation: 3,
    // paddingVertical: '5rem',
    // paddingHorizontal: '5rem',
  },
  detailsText: {
    fontSize: Fonts.size.h4,
    color: '#F5F5F5',
    fontWeight: 'bold',
    textAlign: 'left',
  },
  bottomBtnView: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    bottom: '6rem',
    position: 'absolute',
    alignItems: 'center',
  },
  bottomBtnTouch: {
    width: '70rem',
    height: '70rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '30rem',
    backgroundColor: Colors.white,
    borderWidth: '1rem',
    borderColor: Colors.lightGray,
  },
  bottomBtnImg: {
    width: '50rem',
    height: '50rem',
  },
  bottomCenterBtnTouch: {
    width: '90rem',
    height: '90rem',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '30rem',
    backgroundColor: Colors.white,
    borderWidth: '1rem',
    borderColor: Colors.lightGray,
  },
  cardsSwipeContainer: {
    flex: '1rem',
    justifyContent: 'flex-end',
    paddingTop: '40rem',
    zIndex: '1rem',
    elevation: '1rem',
  },
  cardContainer: {
    width: '98%',
    height: '100%',
    // borderRadius: '13rem',
    overflow: 'hidden',
    borderTopLeftRadius: '15rem',
    borderTopRightRadius: '15rem',
  },
  card: {
    width: '97.2%',
    height: '86%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomLeftRadius: '15rem',
    borderBottomRightRadius: '15rem',
    shadowColor: '#000000',
    shadowOffset: {
      width: '0rem',
      height: '8rem',
    },
    shadowOpacity: '0.07rem',
    shadowRadius: '15rem',
    elevation: '6rem',
  },
  cardImg: {
    width: '100%',
    height: '100%',
    // borderRadius: '13rem',
  },
  cardImgView: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  noMoreCard: {
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  controlRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    width: '100%',
    paddingHorizontal: '20rem',
    marginTop: '22rem',
    marginBottom: '30rem',
  },
  button: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '70rem',
    height: '70rem',
    padding: '14rem',
    borderWidth: '3rem',
    borderRadius: '35rem',
  },
  rightBtn: {
    borderColor: Colors.green,
  },
  leftBtn: {
    borderColor: Colors.red,
  },
  likeIcon: {
    width: '40rem',
    height: '40rem',
    top: '-3rem',
  },
  dislikeIcon: {
    width: '40rem',
    height: '40rem',
    top: '3rem',
  },
  nope: {
    borderWidth: '5rem',
    borderRadius: '6rem',
    padding: '8rem',
    marginRight: '30rem',
    marginTop: '25rem',
    borderColor: Colors.red,
    transform: [{rotateZ: '22deg'}],
  },
  nopeLabel: {
    // fontSize: '32rem',
    color: Colors.red,
    // fontWeight: 'bold',
    fontSize: Fonts.size.h3,
  },
  like: {
    borderWidth: '5rem',
    borderRadius: '6rem',
    padding: '8rem',
    marginLeft: '30rem',
    marginTop: '20rem',
    borderColor: Colors.lightGreen,
    transform: [{rotateZ: '-22deg'}],
  },
  likeLabel: {
    // fontSize: 32,
    color: Colors.lightGreen,
    // fontWeight: 'bold',
    fontSize: Fonts.size.h3,
  },
  requestIcon: {
    width: '40rem',
    height: '40rem',
    top: '3rem',
  },
  favrouiteIcon: {
    width: '40rem',
    height: '40rem',
    top: '3rem',
  },
  buttonName: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // width: 70,
    // height: 70,
    padding: '14rem',
    borderRadius: '35rem',
  },
  midlBtn: {
    borderColor: Colors.yellow,
  },
  controlNameRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '97.2%',
    // paddingHorizontal: '20rem',
    // marginTop: '22rem',
    // marginBottom: '30rem',
    backgroundColor: Colors.black,
    marginHorizontal: '5.4rem',
    // borderRadius:'20rem',
    paddingVertical: '15rem',
    borderBottomLeftRadius: '15rem',
    borderBottomRightRadius: '15rem',
  },
  btnText: {
    color: Colors.white,
    fontSize: Fonts.size.h4,
  },
});

export default styles;
